import type { Plugin } from 'vue';
import {
  accordionPlugin,
  affixPlugin,
  backdropPlugin,
  badgePlugin,
  breadcrumbsPlugin,
  buttonPlugin,
  buttonEmptyPlugin,
  buttonLinkPlugin,
  configProviderPlugin,
  dialogPlugin,
  drawerPlugin,
  dropdownPlugin,
  fancyboxPlugin,
  formPlugin,
  formItemPlugin,
  checkboxPlugin,
  checkboxGroupPlugin,
  imagePlugin,
  inputPlugin,
  inputCodePlugin,
  inputFilePlugin,
  inputMaskPlugin,
  inputNumberPlugin,
  inputPasswordPlugin,
  inputRangePlugin,
  placeholderIconPlugin,
  placeholderBreadcrumbsPlugin,
  placeholderButtonPlugin,
  placeholderHPlugin,
  pageLayoutPlugin,
  paginationPlugin,
  placeholderImagePlugin,
  placeholderInputPlugin,
  placeholderPlugin,
  placeholderTextPlugin,
  pricePlugin,
  colPlugin,
  radioPlugin,
  rowPlugin,
  radioButtonPlugin,
  radioGroupPlugin,
  containerPlugin,
  labelPlugin,
  labelGroupPlugin,
  linkPlugin,
  layoutPlugin,
  scrollbarPlugin,
  sectionPlugin,
  segmentPlugin,
  selectPlugin,
  tabsPlugin,
  tagPlugin,
  textPlugin,
  spinnerPlugin,
  splitLayoutPlugin,
  tagsGroupPlugin
} from './components';
import { loadingPlugin, visiblePlugin, clickOutsidePlugin } from './directives';

export const globalInstall: Plugin = {
  install (app) {
    // install components
    app.use(accordionPlugin);
    app.use(affixPlugin);
    app.use(backdropPlugin);
    app.use(badgePlugin);
    app.use(breadcrumbsPlugin);
    app.use(buttonPlugin);
    app.use(buttonEmptyPlugin);
    app.use(buttonLinkPlugin);
    app.use(configProviderPlugin);
    app.use(dialogPlugin);
    app.use(drawerPlugin);
    app.use(dropdownPlugin);
    app.use(fancyboxPlugin);
    app.use(formPlugin);
    app.use(formItemPlugin);
    app.use(checkboxPlugin);
    app.use(checkboxGroupPlugin);
    app.use(imagePlugin);
    app.use(inputPlugin);
    app.use(inputCodePlugin);
    app.use(inputFilePlugin);
    app.use(inputMaskPlugin);
    app.use(inputNumberPlugin);
    app.use(inputPasswordPlugin);
    app.use(inputRangePlugin);
    app.use(placeholderIconPlugin);
    app.use(placeholderBreadcrumbsPlugin);
    app.use(placeholderButtonPlugin);
    app.use(placeholderHPlugin);
    app.use(pageLayoutPlugin);
    app.use(paginationPlugin);
    app.use(placeholderImagePlugin);
    app.use(placeholderInputPlugin);
    app.use(placeholderPlugin);
    app.use(placeholderTextPlugin);
    app.use(pricePlugin);
    app.use(colPlugin);
    app.use(radioPlugin);
    app.use(rowPlugin);
    app.use(radioButtonPlugin);
    app.use(radioGroupPlugin);
    app.use(containerPlugin);
    app.use(labelPlugin);
    app.use(labelGroupPlugin);
    app.use(linkPlugin);
    app.use(layoutPlugin);
    app.use(scrollbarPlugin);
    app.use(sectionPlugin);
    app.use(segmentPlugin);
    app.use(selectPlugin);
    app.use(tabsPlugin);
    app.use(tagPlugin);
    app.use(textPlugin);
    app.use(spinnerPlugin);
    app.use(splitLayoutPlugin);
    app.use(tagsGroupPlugin);

    // install directives
    app.use(loadingPlugin);
    app.use(visiblePlugin);
    app.use(clickOutsidePlugin);
  }
};
